### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by NullHypothesis** [NullHypothesis/exitmap#22]
Test coverage is almost zero at this point, which means that there's quite a bit of code that has never been executed.

**Comment by frankcash** [comment]
I would be interested in helping with this, do you have a preferred starting point?

**Comment by NullHypothesis** [comment]
Great, thanks for your interest, Frank! There's some rudimentary code in `unittests.py` which would be a good starting point. There are several functions in the code (e.g., in `util.py`) that are easy to test in isolation. For others, it might be more difficult.

**Comment by frankcash** [comment]
okay, awesome
