### ISSUE TITLE
Warn user when Stem version is too old

### ISSUE THREAD

**Issue by NullHypothesis** [NullHypothesis/exitmap#28]
When using a Stem version that is too old, we run into the error:
`
ValueError: Extra-info digests should consist of forty hex digits: ...
`
Exitmap should check Stem's version number and warn when it's too old, instead of throwing an obscure exception.

**Comment by jpierz** [comment]
Would you happen to know how far back, version wise, Exitmap will make use of Stem? For example, will this error be thrown even if Stem is one version old?

**Comment by NullHypothesis** [comment]
Good question. I don't know. In fact, this might be caused by a too new Tor version for a too old Stem version, so simply checking Stem's version might not be sufficient.

**Comment by NullHypothesis** [comment]
Alright, Damian, Stem's maintainer, pointed me to this commit: https://gitweb.torproject.org/stem.git/commit/?id=ba8cee3
It's not part of any release yet, but a workaround would be to disable validation.

**Comment by NullHypothesis** [comment]
I now disabled validation in 8534ab1d3fb3e89f8dd6d1f3074f0b462e9e4f63, so older Stem versions don't break.
