### ISSUE TITLE
Use Tor Browser programmatically for scanning

### ISSUE THREAD

**Issue by NullHypothesis** [NullHypothesis/exitmap#46]
We should investigate to which degree we can use Tor Browser programmatically instead of just mimicing its request headers. That would help us detect attacks that target Tor Browser.

**Comment by kyhwana** [comment]
I'm about to submit a bug report for python urllib2 (which exitmap uses)
I modified checktest and ran it against the latest release and all I got was unknown/likely..

**Comment by NullHypothesis** [comment]
This may be useful: https://github.com/webfp/tor-browser-selenium
