### ISSUE TITLE
dnspoison module: IPv6 addresses cause false positives

### ISSUE THREAD

**Issue by nusenu** [NullHypothesis/exitmap#60]
When the exit relay returns IPv6 addresses for a tested domain the dnspoison module claims to have found a DNS poisoning exit, but this is a false positive since the module does not support IPv6 and interprets the returned data as IPv4 address.

This is causing almost daily false positives.

**Comment by dianavfg** [comment]
Hi, at the moment I'm trying to do dns poisoning in ipv6, I found some .py codes. but I have also seen your comment. Could you tell me when you say that the module does not support ipv6 to refer to a specific code or that in general there is no poisoning of dns ipv6?
